Different approach to config.xml schema

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -26,94 +26,36 @@ set -e
 
 case "$1" in
     configure)
-        echo "Initialize configuration"
+        SERVICE_XPATH_NAME="fail2ban"
+        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"
 
-        # Check for XML config
-        if ! omv_config_exists "/config/services/fail2ban"; then
-    	    echo "Initialize Fail2ban plugin configuration"
-    	    DEFAULT_IGNOREIP="127.0.0.1"
-    	    DEFAULT_BANTIME="600"
-    	    DEFAULT_MAXRETRY="3"
-    	    
-            SSH_ENABLED="false"
-            SSH_PORT="ssh"
-            SSH_MAXRETRY="6"
+        if ! omv_config_exists "${SERVICE_XPATH}"; then
+            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
+            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
+            omv_config_add_element "${SERVICE_XPATH}" "loglevel" "3"
+            omv_config_add_element "${SERVICE_XPATH}" "jaildefaults"
+            omv_config_add_element "${SERVICE_XPATH}" "jails"
+            omv_config_add_element "${SERVICE_XPATH}" "filters"
             
-            APACHE_ENABLED="false"
-            APACHE_PORT="http,https"
-            APACHE_MAXRETRY="6"
-
-            PROFTPD_ENABLED="false"
-            PROFTPD_PORT="ftp,ftp-data,ftps,ftps-data"
-            PROFTPD_MAXRETRY="6"
-
-        else
-            echo "Importing previous configuration"
-    	    DEFAULT_IGNOREIP="$(omv_config_get "/config/services/fail2ban/default/ignoreip")"
-    	    DEFAULT_BANTIME="$(omv_config_get "/config/services/fail2ban/default/bantime")"
-    	    DEFAULT_MAXRETRY="$(omv_config_get "/config/services/fail2ban/default/maxretry")"
-    	    
-            SSH_ENABLED="$(omv_config_get "/config/services/fail2ban/ssh/enabled")"
-            SSH_PORT="$(omv_config_get "/config/services/fail2ban/ssh/port")"
-            SSH_MAXRETRY="$(omv_config_get "/config/services/fail2ban/ssh/maxretry")"
-
-            APACHE_ENABLED="$(omv_config_get "/config/services/fail2ban/apache/enabled")"
-            APACHE_PORT="$(omv_config_get "/config/services/fail2ban/apache/port")"
-            APACHE_MAXRETRY="$(omv_config_get "/config/services/fail2ban/apache/maxretry")"
-            
-            PROFTPD_ENABLED="$(omv_config_get "/config/services/fail2ban/proftpd/enabled")"
-            PROFTPD_PORT="$(omv_config_get "/config/services/fail2ban/proftpd/port")"
-            PROFTPD_MAXRETRY="$(omv_config_get "/config/services/fail2ban/proftpd/maxretry")"
-
+            # Stop and prevent fail2ban from starting automatically
+            service fail2ban stop
+            update-rc.d fail2ban disable
         fi
 
-        omv_config_delete "/config/services/fail2ban"
-        
-        object="<default>"
-            object="${object}<ignoreip>${DEFAULT_IGNOREIP}</ignoreip>"
-            object="${object}<bantime>${DEFAULT_BANTIME}</bantime>"
-            object="${object}<maxretry>${DEFAULT_MAXRETRY}</maxretry>"
-        object="${object}</default>"
-        
-        object="${object}<ssh>"
-            object="${object}<enabled>${SSH_ENABLED}</enabled>"
-            object="${object}<port>${SSH_PORT}</port>"
-            object="${object}<maxretry>${SSH_MAXRETRY}</maxretry>"
-        object="${object}</ssh>"
-        
-        object="${object}<apache>"
-            object="${object}<enabled>${APACHE_ENABLED}</enabled>"
-            object="${object}<port>${APACHE_PORT}</port>"
-            object="${object}<maxretry>${APACHE_MAXRETRY}</maxretry>"
-        object="${object}</apache>"
-
-        object="${object}<proftpd>"
-            object="${object}<enabled>${PROFTPD_ENABLED}</enabled>"
-            object="${object}<port>${PROFTPD_PORT}</port>"
-            object="${object}<maxretry>${PROFTPD_MAXRETRY}</maxretry>"
-        object="${object}</proftpd>"
-
-        omv_config_add_element "/config/services" "fail2ban" "${object}" true
-
-
-        service fail2ban stop
-        omv-mkconf fail2ban # Run script to update the configuration
-        service fail2ban start
-
-
+        # Activate package triggers. These triggers are only set during the
+        # package installation.
+        dpkg-trigger update-fixperms
+        dpkg-trigger update-locale
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
     ;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
+        echo "postinst called with unknown argument" >&2
         exit 1
     ;;
 esac
-
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
 
 #DEBHELPER#
 
